kernel-patches/vmtest

- travis-ci/vmtest/run.sh
Temporarily disable failing when RIP warning is detected in dmesg output.
Right now bpf/bpf-next trees have a known warning, so all the builds are
reported as failing, which reduces signal-to-noise ration of test results.
Signed-off-by: Andrii Nakryiko <andriin@fb.com>
> vmtests: don't fail on dmesg RIP warning

- travis-ci/vmtest/build_selftests.sh
- travis-ci/vmtest/run_vmtest.sh
New nightly version is now 13, update all the used versions accordingly.
> vmtest: switch to Clang/LLVM 13

- travis-ci/vmtest/build_selftests.sh
- travis-ci/vmtest/run_vmtest.sh
Clang 13 has BPF code generation regressions, so until we figure this
out and mitigate the regression, let's fix version 12 and get green builds
again.
> vmtest: roll back to Clang/LLVM 12

- travis-ci/vmtest/build_selftests.sh
- travis-ci/vmtest/run_vmtest.sh
Nightly Clang is fixed, revert back to using the latest Clang in tests.
This reverts commit 0d796e7cef1c8c25ed0891147a74b1293d9da21f.
> Revert "vmtest: roll back to Clang/LLVM 12"

- travis-ci/vmtest/build_selftests.sh
- travis-ci/vmtest/run_vmtest.sh
Reverts kernel-patches/vmtest#6
Latest Clang nightly seems to be OK.
> Revert "vmtest: pin Clang/LLVM to version 12 temporarily"

- .travis.yml
Travis CI by default clones with --depth=50, which results in unnecessarily
big amount of data fetched on every build. Currently it takes about 86 seconds
to check out the repo. Let's see if reducing the depth to 3 will save some
time and traffic.
> travis-ci: perform very shallow Git clone

- .github/workflows/test.yml
Use recent Github Actions' concurrency group functionality ([0]) to ensure
that we only run the latest version of a PR.
This seems to work fine for libbpf CI ([1]).
[0] https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
[1] https://github.com/libbpf/libbpf/commit/0db006d28efd88650dabcf85c8000d788128262a
> ci: make sure to cancel in-flight test runs when PR is updated

- travis-ci/vmtest/helpers.sh
Github action require "::endgroup::" to close the group
> Fix output grouping

- travis-ci/vmtest/run_selftests.sh
This PR adds a call to test_bpftool_synctypes.py to run_selftests.sh. The objective of this script is to make sure that the different parts of bpftool that should be updated on BPF UAPI changes (type lists, help messages, documentation, bash completion) do remain in sync between them, and with the UAPI headers from the kernel. The motivation to have it in the CI is to effectively make sure that new patchsets consistently update all those parts when necessary.
Notes:
- ~The new section in run_selftests.sh is called `Testing bpftool`, but this is not entirely correct. We don't test bpftool itself (only check that different pieces of its code are in sync), whereas _other_ scripts that are part of the BPF selftests suite _do_ test bpftool, outside of this new section. Not sure if something …
> ci: run script to test bpftool types/options sync

- travis-ci/vmtest/run_selftests.sh
Follow-up to https://github.com/kernel-patches/vmtest/pull/22.
We defined `bpftool_checks` but never call it: let's do so.
> ci: do run (previously defined) bpftool_checks

- .github/workflows/test.yml
Adds two optional step in CI workflow that clones bpf-next tree, these steps
only runs out of "kernel-patches/bpf" repo, this will allow testing CI scripts
on vmtest repo PRs.
> Enable CI testing for PRs in vmtest repo

- travis-ci/vmtest/run.sh
- travis-ci/vmtest/run_selftests.sh
This is another take at #22 and #23 (reverted in this PR and #24, respectively, because we currently have no Python3 installed in the VM image).
Things should go better this time, since we have the equivalent PR working in libbpf at https://github.com/libbpf/libbpf/pull/352.
> ci: check bpftool types/options sync (v2)

- travis-ci/vmtest/run.sh
using tip from [0], make linux reboot immediately after a kernel panic, and make qemu exit on reboot attempts.
[0] https://unix.stackexchange.com/questions/443017/can-i-make-qemu-exit-with-failure-on-kernel-panic
> Avoid hanging on kernel panics

- .github/workflows/test.yml
the normal runtime is about 40-50minutes, there should be still plenty of room
> Set timeout to 1.5H instead of default 6H

- travis-ci/vmtest/diffs/0002-x86-setup-Explicitly-include-acpi.h.patch
Add ea7b4244b365 ("x86/setup: Explicitly include acpi.h") to fix bpf tree
build.
> [ci] Add temporary patch fix for bpf tree

- travis-ci/vmtest/run.sh
The bpftool checks work as expected when the CI runs, except that they do not set any error status code for the script on error, which means that the failures are lost among the logs and not reported in a clear way to the reviewers.
Let's account for the status of bpftool checks when exiting from run.sh
[EDIT] Let's also create a summary for the different group tests, at the end of the test logs, under the folded sections. This summary may be extended in the future with a more detailed overview of the tests running in the VM.
**Warning:** Submitted as a PR for discussion and for validation through the CI. Before merging, we should address the current inconsistencies reported by `test_bpftool_synctypes.py`, or we will cause the next CI runs to fail.
> ci: return with non-zero status code if bpftool checks fail

- travis-ci/vmtest/diffs/0004-bpf-sockmap-Attach-map-progs-to-psock-early-for-feat.diff
- travis-ci/vmtest/diffs/0005-bpf-sockmap-Re-evaluate-proto-ops-when-psock-is-remo.diff
Patch up bpf-next tree with John's fixes from bpf tree to unblock
bpf-next CI runs.
> diffs: add two bpf tree fixes for test_maps

- travis-ci/vmtest/helpers.sh
- travis-ci/vmtest/run.sh
- travis-ci/vmtest/run_selftests.sh
- travis-ci/vmtest/run_vmtest.sh
As a follow-up to the recent introduction of a “final summary” of the selftest results in the CI Action logs, make the different groups of selftests (`test_progs`, `test_progs-no_alu32`, `test_maps`, `test_verifier`) print their results individually.
To do:
> Split results per group of selftests in final summary

- travis-ci/vmtest/run.sh
The check on the `$exitstatus` collected from the `/exitstatus` file was changed in a recent commit, and is not correct. Let's fix it. We consider that we failed to read the exit status if we get something other than an integer. This might happen if awk fails because it cannot access the file, for example.
> ci: fix test on exitstatus

- .github/actions/vmtest/latest.config
Add necessary kernel config values to make BPF_PROG_TYPE_LIRC_MODE2
programs work.
> ci: add LIRC kernel configs

- travis-ci/vmtest/run_selftests.sh
This will make CI run faster on new self-hosted runner with more cpus
> use "-j" for test_progs if core count is over than 2

- travis-ci/vmtest/run_selftests.sh
Limit test_maps to running on at most 4 CPUs to avoid excessive memory
usage due to a storm of BPF maps created rapidly on lots of CPU cores.
> run_selftests: limit test_maps parallelism to avoid OOM

- travis-ci/diffs/0001-selftests-bpf-fix-uprobe-offset-calculation-in-selft.diff
Use ff943683f8a6 ("selftests/bpf: fix uprobe offset calculation in selftests")
to fix bpf tree selftests.
> ci: fix bpf tree selftest by applying temporary patch from bpf-next

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest
Multi-kprobe is currently not implemented on x86-64, so blacklist them
temporarily.
> ci: blacklist tests relying on multi-kprobe

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest
Now that x86-64 implementation of multi-kprobe landed, enable selftests
again.
> ci: unblacklist multi-kprobe tests

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest.s390x
libc.so.6 can't be currently resolved in CI for s390x arch.
> ci: blacklist attach_probe and uprobe_autoattach tests on s390x

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest.s390x
This reverts commit 260b6be0f2f6f645e61d73c6490976f9352c708d.
> Revert "ci: blacklist attach_probe and uprobe_autoattach tests on s390x"

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest.s390x
libbpf doesn't support USDTs on s390x yet.
> ci: blacklist USDT selftests on s390x

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest.s390x
It is extremely flaky on s390x, silence it.
> ci: blacklist tc_redirect/tc_redirect_dtime on s390x

- travis-ci/diffs/0001-selftests-bpf-Limit-unroll_count-for-pyperf600-test.diff
"Backport" Yonghong's fix ([0]) for selftests preventing Clang from
crashing when compiling pyperf600 test.
[0] 8c89b5db7a28 ("selftests/bpf: Limit unroll_count for pyperf600 test")
> ci: temporary fix for bpf tree preventing Clang crash

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest
- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest.s390x
> ci: blacklist mptcp test on s390x, kprobe_multi_test/bench_attach everywhere

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest.s390x
The xdp_syncookie test uses kfunc, and BPF JIT doesn't support kfunc on
s390x.
Signed-off-by: Maxim Mikityanskiy <maximmi@nvidia.com>
> ci: blacklist xdp_syncookie on s390x

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest.s390x
Another test with BPF trampoline dependency. BPF trampoline isn't
supported by s390x.
> ci: blacklist unpriv_bpf_disabled on s390x due to BPF trampoline use

- travis-ci/diffs/0001-selftests-bpf-fix-stacktrace_build_id-with-missing-k.diff
Temporarily "backport" the fix before the actual fix lands in bpf tree.
Signed-off-by: Song Liu <song@kernel.org>
> ci: temporary fix for selftest stacktrace_build_id

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest
Waiting for Clang nightly to be updated with ENUM64 support.
> ci: blacklist enum64 tests temporarily

- travis-ci/vmtest/configs/blacklist/BLACKLIST-latest
Newest Clang emits ENUM64 types, but bpf tree doesn't yet have libbpf
that can handle them.
> ci: blacklist few core_reloc subtests which got ENUM64s in them

- .github/workflows/test.yml
This patch was applied before as cd9dc8915cb4, but reverted by mistake
in 7487c6523cc9.
Context: https://github.com/kernel-patches/vmtest/issues/41
> kernel-patches/vmtest is an exception here, not the kernel-patches/bpf
We don't want a hardcoded condition on `kernel-patches/bpf` to enable
the CI for vmtest, because it makes it harder to reuse the CI on
different repos in the future (think net/net-next) or on different forks
of bpf-next. Instead, let's copy the sources only when running the
GitHub Action on the kernel-patches/vmtest repository.
Next step should be to create a separate .yml workflow description,
specific to kernel-patches/vmtest.
Fixes: fa07d13393d0 ("Enable CI testing for PRs in vmtest repo")
Signed-off-by: Paul Chaignon <paul@cilium.io>
Signed-off-by: Quentin Monnet …
> Reverse condition for copying the Linux sources

- .github/workflows/test.yml
This change removes the setting of the AUTHOR_EMAIL variable. To the
degree I can tell, this variable is not used. A successful CI run
without it confirmed this suspicion.
> Remove setting of AUTHOR_EMAIL environment variable

- .github/workflows/test.yml
We have seen cases of timeouts in the CI where a GitHub-hosted runner
was used for test execution and that slowed down everything from setup
to kernel build to running of tests.
Given that we have sufficient EC2 runners, which are beefier than
GitHub-hosted ones and, hence, can execute runs in a more timely fashion
and with fewer chances for timeouts, let's make sure to only use
self-hosted runners.
The self-hosted label is automatically assigned to all self-hosted
runners [0]. With this change we make sure to execute jobs only where
this label is present.
[0] https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-self-hosted-runners
> Run on self-hosted runners

- travis-ci/vmtest/configs/DENYLIST
- travis-ci/vmtest/run_selftests.sh
We would like to have the possibility of quickly adding additional allow
or deny lists compared to what the upstream kernel already provides.
This change introduces the infrastructure for doing so. It also brings
back the non-architecture specific deny list removed by fba2b3da955c8
("Use deny/allow lists from upstream") which constitutes the difference
over what upstream Linux now contains, as we have seen increased
flakiness in recent CI runs.
> Add support for allow/deny list additions

- .github/workflows/test.yml
We started to use array of tags during the CI
configuration print, but GH actions do not expand
array and just print 'Array' literal which is
confusing
Signed-off-by: Mykola Lysenko <mykolal@fb.com>
> ci: fix printing of currently used configuration

- .github/workflows/test.yml
Development on LLVM 16 has started and version 15 is no longer available
in the repository we install it from. Bump the version we use
accordingly.
> Bump LLVM version we use to 16

- travis-ci/diffs/0001-x86-kprobes-Update-kcb-status-flag-after-singlestepp.diff
When using a more minimal configuration (as it landed upstream in the
bpf-next tree), we saw frequent NULL pointer dereferences in the kernel
causing VM crashes and CI run failures as a result.
The issue has been fixed [0] in a different repository and so for now we
just carry around the patch here.
[0] https://lore.kernel.org/bpf/165942025658.342061.12452378391879093249.stgit@devnote2/
> Add patch fixing NULL pointer dereference

- travis-ci/vmtest/run_selftests.sh
We support excluding and including of tests in CI runs based on deny and
allow lists, respectively, maintained in separate files. Currently these
lists are fed to test_progs via the -b (and -t) argument. This argument
is evaluated as sub-string match, meaning that for the string 'align',
for example, it would prevent both 'align-8' and 'misaligned' from
running (if deny-listed). Most of the time that's not what we want: we'd
rather specify complete names. If the desire truly is for an entry to
match multiple items, that should be made more explicit via the usage of
pattern/wildcard syntax.
With this change we switch over to using -d/-a for passing deny and
allow information to the program, which treats arguments as exact
strings, but optionally allows for wildcard usage.
Signed-off-by: …
> Use pattern match for allow/deny list logic

- .github/workflows/test.yml
Whenever the current LLVM version is bumped, we have to adjust the
version to use in CI, because snapshot packages of the previous version
may be removed from distribution repositories and can no longer be
installed. Furthermore, this adjustment has to happen across
repositories and there are dependencies between them, making the process
tricky and partly serial and the changes non-atomic.
With recent changes we have introduced an action that contains the LLVM
version to use in an action in the central libbpf/ci repository that
constitutes the source of truth.
With this change we make use of this action to determine the LLVM
toolchain with which to work.
> Replace hardcoded LLVM version

- .github/workflows/test.yml
We run tests in various configurations: on x86_64 and s390x, with gcc
and clang toolchains. To define the setups to use we rely on the job
matrix feature of GitHub Actions [0].
In the future we would like to run the selftests in parallel in an
attempt to minimize overall CI runtime. As a first step towards getting
there, we want the running of selftests to be a separate job after the
building step.
Both running and building need to honor the job matrix, but GitHub
Actions does not allow us to simple configure the same matrix for
multiple jobs.
In order to make that possible, this change uses the job output feature
to "generate" the matrix, which can subsequently be used from various
locations (including different jobs). To make that work in the job
context, we now have to define the …
> Make job matrix reusable

- travis-ci/vmtest/run_selftests.sh
We should include the deny and allow lists used somewhere in the output
of our CI runs in order to improve debuggability in general. With this
change we print out these lists once assembled.
> Print allow and deny lists

- travis-ci/vmtest/run_selftests.sh
This change factors out a new function, test_progs_noalu, in the
run_selftests.sh script. Having this function available will make it
easier for us to run tests conditionally later on, but it's also a
matter of having one function for one binary.
> Factor out test_progs_noalu function

- .github/workflows/test.yml
Our CI job matrix already includes the kernel version we run on, so
there is no need for us to hard code the string 'LATEST' explicitly
later on. Use the matrix defined version instead.
> Use matrix.kernel instead of hardcoding LATEST

- .github/workflows/test.yml
The path to the file system image used by our invocation of Qemu is
currently hard coded to /tmp/root.img somewhere in a different
repository. With
https://github.com/libbpf/ci/commit/da44c0b6ee29ec53776c1303f7ac790b7e337db5
landed we have the option of specifying it explicitly from here. Let's
do just that, so that we can remove the default value from libbpf/ci
altogether.
> Explicitly specify Qemu image path to use

- travis-ci/vmtest/run_selftests.sh
This change adjusts the run_selftests.sh script to accept an optional
list of arguments specifying the tests to run. We will make use of it
once we run selftests in parallel.
> Support running of individual tests

- travis-ci/diffs/0001-selftests-bpf-Add-lru_bug-to-s390x-deny-list.diff
Recently bpf got merged into bpf-next. That merge pulled in change
de7b9927105b ("selftests/bpf: Add test for prealloc_lru_pop bug") but
did not include 27e23836ce22 ("selftests/bpf: Add lru_bug to s390x deny
list") yet.
As a result, we are now seeing the lru_bug selftest run (and fail) on CI
runs of bpf-next.
Backport the fix to get CI runs back into green state.
> Add patch adding lru_bug to deny list

- travis-ci/vmtest/configs/DENYLIST.s390x
This change adds the lru_bug to the s390x denylist. It was already added
to the upstream denylist of bpf, but not bpf-next. Pull request #123 [0]
added the original patch for bpf to the repository, but with recent
upstream changes to bpf-next, it stopped applying cleanly.
[0] https://github.com/kernel-patches/vmtest/pull/123
> Add lru_bug to s390x denylist

- travis-ci/vmtest/run_selftests.sh
As a follow up to 806b2eef533c ("Factor out test_progs_noalu function")
and taking into account feedback [0], this change renames the
test_progs_noalu function to test_progs_no_alu32, to stay closer to the
name of the binary being invoked.
[0] https://github.com/kernel-patches/vmtest/pull/124#discussion_r953175641
> Rename test_progs_noalu function to test_progs_no_alu32

- .github/workflows/test.yml
The kernel-patches organization hosts their own GitHub Actions runners
which generally are much quicker at running individual CI jobs. To that
end, aecee1ab23bf ("Run on self-hosted runners") prevented the running
on GitHub-hosted ones altogether.
We would still provide the possibility for users of the BPF CI system to
trigger runs without having to create a pull request against a
repository in said org [0] (which, in the future, could conceivably require
approval before executing actions).
To enable this use case, this change requires the self-hosted tag for
build and selftest jobs only when running inside the kernel-patches
organization.
Furthermore, because GitHub does not have any s390x runners, do not test
on these when outside of kernel-patches organization.
[0] …
> Only require self-hosted runners in kernel-patches organization

- .github/workflows/test.yml
We currently implicitly rely on the default value for the kernel version
of the prepare-rootfs action. That's counter intuitive, because we
explicitly carry around the kernel version to use in our job matrix.
Let's make the specification explicit instead.
> Explicitly provide kernel version to use

- .github/workflows/test.yml
With https://github.com/libbpf/ci/pull/36 merged the run-qemu action now
accepts an additional argument, `kernel-root`.
Provide it to the action with the value appropriate for this repository.
> Provide kernel-root argument to run-qemu action

- travis-ci/vmtest/configs/DENYLIST.s390x
After some recent test infra changes, the BPF prog `usdt0` associated with these tests started failing verifier:
```
R2 unbounded memory access, make sure to bounds check any such access
processed 89 insns (limit 1000000) max_states_per_insn 0 total_states 8 peak_states 8 mark_read 3
-- END PROG LOAD LOG --
libbpf: prog 'usdt0': failed to load: -13
```
Add these tests to blacklist temporarily so as not to interfere with test signal for other changes. 
Signed-off-by: Dave Marchevsky <davemarchevsky@fb.com>
> Add usdt/basic and usdt/multispec to s390x denylist

- .github/workflows/test.yml
Not all repositories within the "kernel-patches" organization are using self-hosted runner. For instance, "bpf-rc" repo is not, "rcu-rc" is not. "rcu" may in the future.
This change only enables self-hosted on a selected list of repositories within a "kernel-patches".
> [runners] Only pick up self-hosted runners on a handful or repos

- .github/workflows/test.yml
zstd offers better compression ration and is multi-threaded so it can leverage the CPUs available in the host to compress/decompress faster. With better compression ratio, the size of the artifacts  uploaded/downloaded will be smaller hence faster upload/download.
> [artifacts] Use zstd to compress artifacts

- ci/vmtest/configs/DENYLIST.s390x
The deny_namespace selftest was recently added to validate the userns_create LSM hooks. The test does not work on s390x because LSM uses BPF trampoline.
8206e4e95230 ("selftests/bpf: Add selftest deny_namespace to s390x deny list") was added to the bpf-next tree, but the bpf CI runs are still failing because the commit is not in that tree. So as to avoid merge conflicts, let's just blacklist it on vmtest.
Signed-off-by: David Vernet <void@manifault.com>
> Add deny_namespace to DENYLIST.s390x configuration

- .github/workflows/test.yml
Actions runs started showing the error:
> build for x86_64 with llvm-16
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
This change sets actions/checkout to v3, which is an upgrade from v2 in out first use case, and a pinning to v3 vs main for the second use case.
> update actions/checkout to v3

- ci/vmtest/configs/DENYLIST
This was fixed as part of libbpf/ci#52
> denylist: remove verify_pkcs7_sig from DENYLIST

- .github/workflows/lint.yml
Our vmtest repository files (including GitHub Actions workflow definitions) get injected into the Linux source code repository in order to trigger CI runs on it. As a result, any workflows defined here will run there as well. That is fine for our actual Linux tests, but not so for the linting of shell scripts: the linter was intended to only cover vmtest shell scripts itself.
Make linting conditional on the repository we are run in to prevent spurious invocations.
> Run shellcheck only in vmtest repository

- .github/workflows/test.yml
We have seen cases where the new parallel tests get stuck and we hit the overall workload timeout (e.g., [0]). That is despite us having enabled various panic on {soft lockup, hard lockup, task hang} settings already. That can happen, for example, if test_progs itself (i.e., the user space portion) encounters a deadlock.
The test being marked as failed in such a case is causing some noise in Patchwork. To work around this issue, this change introduces a second level of timeouts, specifically for parallel job runs. Because these timeouts are now attached directly to the job, which in turn is marked as continue-on-error, they no longer cause failure of the overall workflow.
I have verified this behavior with the following GitHub Actions configuration, in which the "Test" step hit the 1 …
> Gracefully fail parallel tests getting stuck

- .github/workflows/test.yml
Commit 3556ce9f9c856 ("Gracefully fail parallel tests getting stuck") attempted to set dedicated timeouts for experimental jobs. However, we missed to actually set the timeouts on said job, and instead assumed it was picked up automatically.
That's not the case. Do it now explicitly.
> Actually set timeouts for experimental runs

- ci/diffs/0001-bpftool-Fix-NULL-pointer-dereference-when-pin-PROG-M.diff
- ci/diffs/0002-tools-headers-uapi-pull-in-stddef.h-to-fix-BPF-selft.diff
Temporarily backport [0] until proper fixes make it to bpf-next from bpf tree.
[0] https://patchwork.kernel.org/project/netdevbpf/list/?series=691352&state=*
> diffs: fix bpf-next build failures

- .github/workflows/test.yml
If we are not in a vetted repo, only run on x86_64's ubuntu-latest runners (GH runners)
Otherwise, run on runners that have both `self-hosted` and `uname -m` labels.
This will allow to move self-hosted runners at org level and have them being used across the different repos we support under kernel-patches and make better use of the pool of runners.
> workflow: re-arrange runner selection logic

- .github/workflows/test.yml
As of https://github.com/libbpf/ci/pull/67 a bunch of actions honor KBUILD_OUTPUT. Doing so will make it possible to separate source code from build artifacts, which in turn may allow us to support incremental kernel compilation in CI down the line.
Irrespective of these future changes, actions pertaining the kernel build now ask for an additional input defining where to store or expect build artifacts. Provide it.
> ci: Provide KBUILD_OUTPUT to actions asking for it

- .github/workflows/test.yml
- ci/diffs/0001-x86-vdso-Conditionally-export-__vdso_sgx_enter_enclave.patch
- ci/vmtest/configs/DENYLIST.aarch64
> ci: Enable CI on aarch64

- .github/workflows/test.yml
This change introduces the means for performing incremental kernel builds in CI in order to decrease overall CI turn-around times. We piggy back (and rely) on the kernel's own make-based build infrastructure for that purpose. Specifically, with https://github.com/libbpf/ci/pull/67 we have set the stage for separating build artifacts from source code. With the change at hand we use this capability in conjunction with the `actions/cache` [0] GitHub Actions action to share intermediate build artifacts between CI runs, enabling the kernel build to only rebuild what has changed, as opposed to everything unconditionally.
There are several wrinkles to doing so. The first one is that GitHub Actions checks out the source code anew every time a workflow is run. Because git does not store file meta …
> Cache kernel build artifacts and perform incremental kernel builds

- .github/workflows/test.yml
We have seen some architecture related build failures with the incremental build logic in place. E.g.,
https://github.com/kernel-patches/bpf/actions/runs/3441158955/jobs/5740411241#step:10:49
We can see that we picked up the cache from
kbuild-output-Linux-gcc-1668121889-67377655e58ae24ef2125c05e4dcfeb2e59d64dc. That cache was actually created on x86_64, but the job is running aarch64.
The reason that is done is because we are using `runner.os` as part of the key, when really we should be using `matrix.arch`. Let's use the latter instead. We only currently have one OS we test on.
> Use matrix.arch as cache key identifier

- .github/workflows/test.yml
With commit 0f78398f5f30 ("Include base branch name in cache key identifier") we still have one problem: GitHub uses different attributes to represent the various branches/refs of interest in different contexts. E.g., in pull requests it populates the `base_ref` field, whereas for pushes it is empty. Similarly, `ref_name` refers to different things.
With this change we "generate" the branch name to include in the cache key identifier with keeping that into account. Basically, when we want to create the cache (on the "push" path) we can rely on `ref_name`, whereas when we are interested in pulling the cache (pull request), we need to use `base_ref`.
> Use a different branch key depending on event received

- .github/workflows/test.yml
Commit 31605ba85acb ("Work more with upstream commit SHA-1") adjusted the commit SHA-1 that we use as the actual base commit for incremental builds but also as part of the cache key identifier. When earlier we referenced a temporary KPD-created commit, we now use an upstream commit that has meaning outside the specific repository being worked on.
However, the way we got this upstream commit was not particularly great, as it made an implicit assumption about KPD creating exactly a single commit on top of upstream (i.e., we inferred that HEAD^ was the first upstream commit).
This change makes upstream commit identification more robust, by removing this assumption. Specifically, we piggy back on the branch name (in case of push) or base branch (in case of pull request), and remove the _base …
> Use a more robust way of identifying the baseline upstream commit

- ci/vmtest/configs/DENYLIST
Since the test case was renamed, the DENYLIST should also be updated.
Signed-off-by: Kui-Feng Lee <kuifeng@fb.com>
> selftests/bpf: Change the name kprobe_multi_test/bench_attach to kprobe_multi_bench_attach in DENYLIST.

- .github/workflows/test.yml
Depending on which run we look at, the transfer of build artifacts between the build and test stages of the workflow is among the most expensive steps, where content is compressed multiple times, sent over the network, and later downloaded again over the network and decompressed.
As such, decreasing the number of build artifacts that we include in the transfer may have a large impact. To give two examples:
- On selfhosted (x86) runners [0] uploading artifacts is regularly the longest taking step in the build phase and taring them is not insignificant either.
- On GitHub hosted runners (and with incremental kernel builds) [1] taring artifacts is the single most expensive step and uploading them has a fair contribution as well.
This change minimizes the number of build artifacts we carry …
> Carry fewer build artifacts between build and test stages

- .github/workflows/test.yml
Continuing on the low priority effort of investigating BPF CI runtime bottlenecks and speeding up runs, this change proposes stripping debug information from vmlinux. This information should not be necessary for BPF CI to function and is not expected to affect debugability negatively either.
The uncompressed artifacts are impacted as follows (only looked at x86 LLVM):
```
kbuild-output/vmlinux   390 MB -> 71 MB (-81.79%)
```
The size of of the actually transferred compressed artifacts changed as follows:
```
vmlinux-aarch64-gcc     138 MB -> 61.7 MB (-55.28%)
vmlinux-aarch64-llvm-16 112 MB -> 61.7 MB (-44.91%)
vmlinux-s390x-gcc       128 MB -> 60.5 MB (-52.73%)
vmlinux-x86_64-gcc      185 MB -> 60.0 MB (-67.56%)
vmlinux-x86_64-llvm-16  133 MB -> 59.0 MB (-55.63%)
```
That's based on test …
> Strip debug information from vmlinux

- ci/vmtest/configs/DENYLIST.aarch64
It's very unstable and frequently fails.
> ci/aarch64: temporarily disable xdp_bonding/xdp_bonding_redirect_multi subtest

- ci/vmtest/configs/DENYLIST.aarch64
It fails frequently in CI on the bpf branch. Andrii already disabled the xdp_bonding/xdp_bonding_redirect_multi subtest in f6c52be043fa ("ci/aarch64: temporarily disable xdp_bonding/xdp_bonding_redirect_multi subtest"), so let's do the same for another failing subtest.
Signed-off-by: David Vernet <void@manifault.com>
> ci/aarch64: temporarily disable xdp_bonding/xdp_bonding_activebackup

- ci/vmtest/configs/DENYLIST.aarch64
We've been seeing frequent random failures of various testcases in the xdp_bonding suite on aarch64. A couple of other commits disabled specific testcases, but others are flakily failing as well. Let's just disable the whole suite until we investigate, as the tests aren't providing any value at the moment anyways if we're just disabling them when they fail.
Signed-off-by: David Vernet <void@manifault.com>
> ci/aarch64: temporarily disable entire xdp_bonding suite on aarch64

- ci/diffs/0001-Revert-arch-fix-broken-BuildID-for-arm64-and-riscv.patch
Fixes a temporary issue with CI on s390 caused by one of the upstream commits. All recent pull requests are failing because of the build issue on s390, e.g.:
- https://github.com/kernel-patches/bpf/actions/runs/3851652311
- https://github.com/kernel-patches/bpf/actions/runs/3851642638
- https://github.com/kernel-patches/bpf/actions/runs/3851641331
This LKML link discusses the issue:
https://lkml.org/lkml/2023/1/2/30
The suggestion is to revert commit
99cb0d917ffa1ab628bb67364ca9b162c07699b1 .
I did this for my pull request and it worked:
https://github.com/kernel-patches/bpf/pull/4299
Signed-off-by: Eduard Zingerman <eddyz87@gmail.com>
> ci/s390: fix CI issue with s390 build

- .github/workflows/test.yml
The s390x workflow is currently broken, caused by what appears to be a versioning mismatch in the LLVM apt snapshot that we consume. That is causing all our CI runs to fail, e.g., here [0].
We have reported the issue upstream [1], but to unblock CI, this change disables testing on s390x until the issue is resolved.
I have scheduled a test run here [2].
[0] https://github.com/kernel-patches/bpf/actions/runs/3944711143 [1] https://github.com/llvm/llvm-project/issues/60128 [2] https://github.com/kernel-patches/bpf/actions/runs/3952315347/jobs/6767240843
> Temporarily disable testing on `s390x`

- .github/workflows/test.yml
It appears as if the LLVM snapshot breakage for s390x has been resolved upstream and we can build and test on this architecture again. This change reverts commit 89413fe98c40f497d7f3fc6435b702ab744a9a12.
> Revert "Temporarily disable testing on s390x"

- ci/diffs/0001-selftests-bpf-Fix-decap_sanity_ns-cleanup.patch
https://lore.kernel.org/all/20230125213817.1424447-8-iii@linux.ibm.com/
> [patch] backport "decap_sanity: sh: 1: Syntax error: Bad fd number" fix

- ci/diffs/0001-bpf-Add-missing-btf_put-to-register_btf_id_dtor_kfun.patch
I'd need this fix for CI failures mentioned in:
https://lore.kernel.org/bpf/Y9KSFaFYc4WLiCa9@krava/T/#m88b67bc1f917e4c6d9418a120b8d6c4164788171
Signed-off-by: Jiri Olsa <jolsa@kernel.org>
> Add patch to fix CI for bpf_testmof kfuncs move

- ci/diffs/0001-selftests-bpf-Fix-compilation-errors-Assign-a-value-.patch
The bpf tree selftests build is currently failing due to errors such as [0]. The fix is in [1], so let's pull that into vmtest to fix CI. We can subsequently decide whether to crossport the patch to the bpf tree.
[0]: https://github.com/kernel-patches/bpf/actions/runs/4351182169/jobs/7602593192
[1]: https://lore.kernel.org/bpf/tencent_CB281722B3C1BD504C16CDE586CACC2BE706@qq.com/
> diffs: Fix selftests build for bpf tree

- ci/vmtest/configs/DENYLIST
The test_ima suite is broken following the 6.3-rc1 merge due to [0]. Until it's fixed (currently being discussed upstream), we should disable it in CI so that runs are unblocked.
[0]: https://lore.kernel.org/all/Y7T1hEhIL5TEmLEN@google.com/
> denylist: Disable test_ima in CI

- .github/workflows/test.yml
In #205 we erronously left test running against llvm 15.
While it is good to know it works, it is probably not worth the resources :)
> [workflow] Only build against llvm-16

- .github/workflows/test.yml
- ci/diffs/0001-selftests-bpf-Add-json-summary-option-to-test_progs.patch
- ci/vmtest/run_selftests.sh
This will cause test_progs* to write a json summary report to disk.             
Later, libbpf/ci actions will be able to collect this file and report a         
summary to the GH UI. libbpf/ci#93 is the companion diff to take                
advantage of this new summary.                                                                                                                                                                
While we could to some extend report to the UI directly from within             
vmtest, doing it from outside the VM environemt will allow us to have           
richer output such as step summary [0].                                         
[0] https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
Example …
> [vmtest] enable --json-summary option

- .github/scripts/veristat-compare.py
- .github/workflows/test.yml
- ci/vmtest/run_selftests.sh
Adds a job to execute veristat on a selected set of object files as a part of the general test pipeline. The job is executed differently for pushes and for pull requests:
- For pushes:
- the kernel is compiled as usual;
- selftests are compiled as well, this is necessary to produce object files that would be used by veristat;
- veristat is executed inside qemu, performance statistics is collected and cached as baseline data.
- For pull requests:
- veristat is executed inside qemu and performance statistics is collected;
- baseline data is restored from cache;
- baseline data is compared to current statistics and step summary page is formed;
- if there are some programs that verified successfully in the baseline but fail verification in current run, the step is marked as failed.
This also …
> [workflow] Add a 'veristat' job

- .github/workflows/test.yml
With bpf-rc repo using GH hosted runners, we have seen cases when bpf actions are waiting on a GH runner. An org is limited to 20 GH runners, when multiple series are being processed, we max them out and bpf repo, which predominantly runs on self-hosted runners, is being idle waiting for a GH runner to free up, perform the action in a couple of seconds and move on.
This change will run set-matrix on any self-hosted machine free and ready to take an action. It does not need any specific arch, so let's pick whatever.
This mean that we will possibly run set-matrix for repo that are not running off self-hosted, on self-hosted, but that should not be a problem. in term of resources.
Here the trick is to evaluate the runner to use as part of a github action expresion so it is executed by …
> run set-matrix on self-hosted runners for kernel-patches org

- .github/workflows/test.yml
For some reason, even though python3 (kernel-patches/runner#23)is installed in s390x runners we still get an error about missing python3 when set-matrix runs off s390x runners:
https://github.com/kernel-patches/bpf/actions/runs/4827368579/jobs/8617270672#step:2:95
Troubleshooting will happen separately, but for now, let's mitigate by forcing running this step on self-hosted + x86_64 runners when the workflow is ran as part of a repository under `kernel-patches` org.
> run set-matrix on x86_64 self-hosted

- ci/diffs/0001-libbpf-btf_dump_type_data_check_overflow-needs-to-co.patch
Add patch from the upstream bpf-next
commit c39028b333f3 ("libbpf: btf_dump_type_data_check_overflow needs to consider BTF_MEMBER_BITFIELD_SIZE") It is to fix the btf_dump selftests failure in the bpf tree.
> diffs: Fix btf_dump selftests failure in bpf tree

- .github/workflows/test.yml
Try to fix
https://github.com/llvm/llvm-project/issues/60128#issuecomment-1532012330. The verisions of clang and libraries are not consistent. We try to move to llvm-17 to see if llvm-17 works without isntroducing other issues.
> Move to llvm-17. (testing)

- .github/workflows/test.yml
Seems like s390x is now broken ([0]) with llvm-version set to 16. Let's try 17.
[0] https://github.com/kernel-patches/bpf/actions/runs/4981534737/jobs/8915910905?pr=3924
> ci: bump llvm version to 17 on s390x

- .github/workflows/test.yml
It is broken and figuring out why will take some time. Meanwhile we have zero testing for all the incoming patches.
> ci: disable llvm-based kernel build on arm64

- ci/diffs/0001-tracing-fprobe-Initialize-ret-valiable-to-fix-smatch.patch
This fixes 39d954200bf6 ("fprobe: Skip exit_handler if entry_handler returns !0"), which causes multiple multi-kprobe tests to fail. Upstream fix was found at [0].
[0]
https://lore.kernel.org/all/168100731160.79534.374827110083836722.stgit@devnote2/#r
> ci: add fix for multi-kprobe as temporary patch

- ci/vmtest/run_selftests.sh
Gain some better visibility for files selected for veristat processing by enabling xtrace inside `run_veristat` function. After this update log output looks as follows:
...
run_veristat - Running veristat
++ awk '/^#/ { next; } { print $0 ".bpf.o"; }' ./veristat.cfg
+ globs='bpf_flow*.bpf.o
bpf_loop_bench*.bpf.o
...
xdp_synproxy*.bpf.o'
+ mkdir -p /command_output
+ ./veristat -o csv -q -e file,prog,verdict,states bpf_flow.bpf.o ...
Failed to open 'test_usdt_multispec.bpf.o': -2
+ echo run_veristat:0
+ '[' -z '' ']'
+ set +x
...
> Enable xtrace when run_selftests.sh:run_veristat() is executed

- ci/diffs/0001-bpf-Clarify-error-expectations-from-bpf_clone_redire.patch
- ci/diffs/0002-selftests-bpf-Update-bpf_clone_redirect-expected-ret.patch
Backport two patches fixing empty_skb selftest.
> ci: temporary fixes from bpf tree to fix bpf-next tree's empty_skb

- .github/actions/veristat_baseline_compare/action.yml
- .github/scripts/compare-veristat-results.sh
- .github/workflows/test.yml
Github cache has S3-like structure, where key is a bucket and files specified in the path argument makes its content.
Due to that fact save and restore actions MUST have the same path argument.
> Fix veristat baseline cache save/restore

- .github/workflows/test.yml
Github actions doesn't allow to access both variable and secrets for workflows triggered by pull requests from forked repositories.
Disabling veristat validation with Meta objects for such PRs since workflow won't be able to download objects due to missing secrets.
Example workflow run: https://github.com/kernel-patches/bpf/actions/runs/6412314917/job/17409487960
> Skip veristat validation with Meta objects for PRs from forks

- .github/scripts/veristat-compare.py
- Use csv.DictReader for veristat results parsing
- Better column name handling with Enum class
- Fix the issue when comparison reports 100% change when both old and new values are zeros
> Refactor veristat-compare.py script

- .github/scripts/veristat-compare.py
New and removed objects have `N/A` value in verdicts fields, ignoring these records.
Add additional safeguard for `verdict_diff` parsing of `N/A` value.
> Fix veristat comparison for completely new and removed bpf objects

- .github/scripts/matrix.py
This changes the logic as to where we run parallel tests to only gcc/x86_64 setup.
We still want to get some signal from those tests, but don't need to have them running on all arch/toolchain pairs.
```
$ GITHUB_REPOSITORY_OWNER=kernel-patches GITHUB_REPOSITORY=kernel-patches/vmtest GITHUB_OUTPUT=/dev/stdout python3 .github/scripts/matrix.py   | cut -d= -f2- | jq . > /tmp/new
$ diff -ruN  /tmp/old /tmp/new
--- /tmp/old	2023-10-26 18:21:56
+++ /tmp/new	2023-10-26 18:22:56
@@ -10,6 +10,7 @@
"toolchain": "gcc",
"llvm-version": "16",
"run_veristat": true,
+      "parallel_tests": true,
"toolchain_full": "gcc",
"tests": {
"include": [
@@ -65,21 +66,11 @@
"timeout_minutes": 360
},
{
-            "test": "test_progs_parallel",
-            "continue_on_error": true,
- …
```
> tests: Run parallel tests on x86_64/gcc only

- ci/diffs/0001-net-bpf-Use-sockopt_lock_sock-in-ip_sock_set_tos.patch
Apply [0] to fix deadlock in bpf-next, while the upstream patch is landing and propagating through net-next.
[0] https://patchwork.kernel.org/project/netdevbpf/patch/20231027182424.1444845-1-yonghong.song@linux.dev/
> ci: apply temporary fix from Yonghong

- ci/diffs/0001-tracing-kprobes-Fix-symbol-counting-logic-by-looking.patch
Upstream patch is pending ([0]), but let's mitigate the issue in CI.
[0] https://lore.kernel.org/all/20231027233126.2073148-1-andrii@kernel.org
> ci: another temporary patch to fix an issue in ftrace/kprobe subsystem

- ci/diffs/0001-selftests-bpf-disable-detection-of-llvm-when-buildin.patch
When selftests run and shellout to bpftool in the VM, llvm is missing and we are failing tests.
> ci/diffs: Disable llvm feature detection for bpftool

- ci/diffs/0001-selftests-bpf-xskxceiver-ksft_print_msg-fix-format-t.patch
Cherry-pick fe69a1b1b6ed ("selftests: bpf: xskxceiver: ksft_print_msg: fix format type error") to fix bpf-next build.
> ci: fix bpf-next build

- ci/vmtest/configs/run_veristat.kernel.cfg
- ci/vmtest/configs/run_veristat.meta.cfg
- ci/vmtest/configs/veristat_meta.cfg
- ci/vmtest/run_selftests.sh
This PR adds a `veristat_meta.cfg` to this repository, meant to be used with the tarball of meta bpf objs.
`run_selftests.sh` is modified to use veristat.cfg files via veristat's `-f` flag. See individual commit summaries for more detail.
> Add veristat.cfg for meta BPF objs

- .github/scripts/matrix.py
Use clang-17 now that it is stable. To catch issues in clang dev version, add clang-18 variant for llvm build on x86-64.
> ci: bump minimum clang to 17 and add 18 to x86-64

- .github/scripts/matrix.py
- ci/diffs/0001-bpf-Fix-a-verifier-bug-due-to-incorrect-branch-offse.patch
- ci/diffs/0001-selftests-bpf-work-around-latest-Clang-smartness.patch
- ci/vmtest/run_selftests.sh
Add test_progs-cpuv4 flavor to the matrix.
> ci: run test_progs-cpuv4 flavor

- .github/scripts/matrix.py
- .github/workflows/kernel-build-test.yml
- .github/workflows/kernel-build.yml
- .github/workflows/test.yml
In addition to default, build `test_prog` with `RELEASE=1` flags, adding `-O2` optimization. Currently it will only work for `llvm` due to fairly old version of `gcc` available on our `ubuntu-20.04` runners. Once we upgrade runners to the latest Ubuntu LTS release, we should be able to enable these builds for `gcc` as well.
> Add release test_progs build

- .github/scripts/compare-veristat-results.sh
- .github/scripts/tests/test_veristat_compare.py
- .github/scripts/veristat_compare.py
- .github/workflows/lint.yml
- .gitignore
- Rename veristat-compare.py into veristat_compare.py to match python naming convention
- Add unittests for parse_tables() method
> Add unittests for veristat_compare script

- ci/diffs/0001-selftests-bpf-Fix-pyperf180-compilation-failure-with.patch
This should be applied to bpf tree. bpf-next already has fix.
> ci: temporary patch to prevent pyper180 compilation failure with non cpuv4

- ci/diffs/0001-bpf-Fix-a-few-selftest-failures-due-to-llvm18-change.patch
Pull in temporary patch to fix bpf/master build.
Suggested-by: Yonghong Song <yonghong.song@linux.dev>
> ci: add bpf-next patch to fix bpf/master build

- ci/vmtest/configs/DENYLIST.s390x
usdt/basic and usdt/multispec tests seem to pass on s390x at the moment. Let's try unblocking them in the CI.
See the [test run](https://github.com/kernel-patches/bpf/actions/runs/7269307249/job/19807144377?pr=6175) that passed on https://github.com/kernel-patches/bpf/pull/6175
> Remove usdt from DENYLIST.s390x

- ci/vmtest/configs/DENYLIST
lwt_reroute started crashing kernel.
tc_links_ingress is failing now.
> ci: denylist two tests causing issues after recent net-next merge

- .github/scripts/veristat_compare.py
- .github/workflows/kernel-build.yml
In preparation of cross-compiling, ensure that we always pass arch parameter to the action.
At a later stage, this parameter will be made required on libbpf-ci.
> build: Always pass architecture to actions

- .github/workflows/kernel-build.yml
We will use this to find out whether or not to install cross-compilation toolchain. Similar to #261
> build: Also pass target arch to setup-env-build

- ci/diffs/0001-tools-resolve_btfids-fix-cross-compilation-to-non-host-endianness.patch
- ci/diffs/0002-tools-resolve_btfids-fix-cross-compilation-to-non-host-endianness.patch
- ci/diffs/0099-selftest-cross-compile.diff
The original patch caused a race condition where 2 rules tried to write to the same files (host-tools and (target) tools directory) causing errors similar to the ones below.
Instead of changing what the scratch dir is, this new patch sets `BPFTOOL` to default to
`TRUNNER_BPFTOOL` instead of `DEFAUlT_BPFTOOL`.
```
2024-02-14T19:49:54.6430105Z   MKDIR
2024-02-14T19:49:54.6547753Z   GEN     /tmp/work/bpf/bpf/tools/testing/selftests/bpf/bpf-helpers.rst
2024-02-14T19:49:54.6552447Z   GEN     /tmp/work/bpf/bpf/tools/testing/selftests/bpf/bpf-syscall.rst
2024-02-14T19:49:54.6698129Z   GEN     /tmp/work/bpf/bpf/tools/testing/selftests/bpf/tools/build/host/libbpf/bpf_helper_defs.h
2024-02-14T19:49:54.6699474Z   GEN     /tmp/work/bpf/bpf/tools/testing/selftests/bpf/tools/build/libbpf/bpf_helper_defs …
```
> ci: Change selftest cross compile patch

- ci/diffs/0099-s390x_nolockdep.diff
s390x's test_map runs slowly in CI due to the different layers of
hypervisors involved.
CI historical data shows that `test_maps` CI job for s390x, over the last 2 weeks, ran in:
mean: 3010s
p50: 2860s
p90: 4140s
p95: 4720s
p99: 5580s
Ilya suggested disabling lockdep based on flamegraph.
Testing in [0] brought down the run time to 516s. Other tests do not seem to benefit/regress.
While this will disminish the value of test_maps for s390x, we still have lockdep coverage for others architectures.
[0]
https://github.com/kernel-patches/bpf/actions/runs/7909828985/job/21591624824
Suggested-by: Ilya Leoshkevich <iii@linux.ibm.com>
> ci: Disable lockdep for s390x

- ci/vmtest/configs/DENYLIST
xdp_bonding/xdp_bonding_features causes bpf-ci fail after net merge.
> denylist: add xdp_bonding/xdp_bonding_features to DENYLIST.

- ci/vmtest/configs/DENYLIST.s390x
This BPF selftest, dummy_st_ops/dummy_init_ptr_arg, case a crash on the s390x platform. [1] It should be disable temporarily.
[1] https://lore.kernel.org/bpf/c9923c1d-971d-4022-8dc8-1364e929d34c@gmail.com/
> denylist: Disable dummy_st_ops/dummy_init_ptr_arg temporarily for s390x.

- ci/vmtest/configs/DENYLIST
Disable "migrate_reuseport/IPv4 TCP_NEW_SYN_RECV reqsk_timer_handler" test that recently became very flaky, causing a lot of CI churn.
> ci: temporary disable very flaky test

- ci/vmtest/configs/DENYLIST
We already disabled ipv4 version, ipv6 is equally flaky, let's disable both.
> ci: disavle ipv6 version of the flaky migrate_reuseport subtest

- ci/diffs/0001-arch-Kconfig-Move-SPECULATION_MITIGATIONS-to-arch-Kc.patch
Upstream is discussing the exact config to ship. In the meanwhile, which would unblock CI.
More discussions here:
https://lore.kernel.org/lkml/20240423045548.1324969-1-song@kernel.org/T/#u
> ci/diffs: Add temporary fix for mitigation config

- ci/diffs/0001-selftests-bpf-fix-inet_csk_accept-prototype-in-test_.patch
Apply temporary patch to fix sk_storage_tracing selftest until upstream fix makes it to both bpf and bpf-next trees.
> ci: fix sk_storage_tracing selftests

- .github/workflows/kernel-build.yml
All other job names are in 'X for Y with Z' form. Normalize the build job name to that form as well for easier parsing.
> ci: build: Make -O2 build name a 3-tuple as well

- ci/diffs/0001-selftests-bpf-Fix-bpf_cookie-and-find_vma-in-nested-.patch
Apply temporary patch to fix bpf-rc, which uses nested VMs.
> ci/diffs: Fix bpf_cookie and find_vma

- ci/diffs/0001-selftests-bpf-Filter-out-_GNU_SOURCE-when-compiling-.patch
Apply as temporary patch upstream fix ([0]) that has to go through bpf/master, so we fix bpf-next tree as well.
[0] https://patchwork.kernel.org/project/netdevbpf/patch/20240725214029.1760809-1-sdf@fomichev.me/
> ci: fix test_cpp build on bpf-next

- ci/vmtest/configs/DENYLIST.rc
- ci/vmtest/vmtest_selftests.sh
Production CI runs on bare-metal self hosted runners. RC CI runs on nested virt GH hosted runners. The difference in platform causes issues with some selftests. So add a DENYLIST to skip tests that are too difficult to debug.
Tested here: https://github.com/kernel-patches/bpf-rc/pull/4201
> Add DENYLIST for RC tier

- .github/scripts/matrix.py
It's flaky and OOMs pretty frequently. We get lots of signal on x86-64, so let's disable it on s390x.
> ci: skip test_maps on s390x

- .github/scripts/matrix.py
This will allow to transition to new container at a later stage without having jobs build and test on different runners because they happen to have both the "self-hosted" and "{arch}" tag.
All our current runners already use the "docker-main" tag.
> scripts: Add docker-main tag to the list of tags required by runs-on

- .github/workflows/kernel-build.yml
s390x is failing due to a pahole change, pin to c2f89dab3f2b0ebb53bab3ed8be32f41cb743c37 to get CI back on track
> pahole: pin to c2f89dab3f2b0ebb53bab3ed8be32f41cb743c37

- ci/vmtest/configs/DENYLIST
This test fails on bpf-next_base, which breaks the CI.
Patch when the test was added: https://lore.kernel.org/bpf/20240722202758.3889061-1-jolsa@kernel.org/T/#u
Broken since: [440b65232829](https://github.com/kernel-patches/bpf/commit/440b65232829fad69947b8de983c13a525cc8871)
cc: @chantra
> Add uprobe_multi_test/consumers to DENYLIST

- ci/vmtest/configs/DENYLIST
The test was fixed in https://git.kernel.org/bpf/bpf-next/c/affb32e4f056
> Remove uprobe_multi_test/consumers from DENYLIST

- ci/vmtest/configs/DENYLIST
It started failing on latest bpf/master, while investigating it, deny it to get back to green state.
> DENYLIST: temporary block build_id/nofault-paged-out subtest

- ci/vmtest/helpers.sh
- ci/vmtest/sched_ext_selftests.sh
- ci/vmtest/vmtest_selftests.sh
See https://github.com/libbpf/ci/pull/149
> ci/vmtest: sync scripts with libbpf/ci#149

- .github/workflows/kernel-build.yml
Remove CACHED_KERNEL_BUILD variable. Instead, always try cache lookup and an incremental kernel build.
Fix base-branch passed to prepare-incremental-build action step:
* use BPF_NEXT_BASE_BRANCH (master) if linux source is downloaded
* use base_ref for pull_requests
* default to ref_name otherwise
Clear build artifacts to avoid caching them on non-push events.
> kernel-build: always try incremental kernel build

- ci/diffs/0499-samples-bpf-fix-samples-compilation.patch
See https://lore.kernel.org/bpf/20241202212154.3174402-1-eddyz87@gmail.com/
> ci/diffs: add a fix for BPF samples build

- .github/workflows/kernel-veristat.yml
Reverts kernel-patches/vmtest#313
A proper fix for veristat-meta requires more changes to the workflows. To be done.
> Revert "kernel-verstat: run veristat-meta on push events"

- .github/workflows/kernel-build-test.yml
- .github/workflows/kernel-build.yml
- .github/workflows/kernel-test.yml
By using sparse checkout in kernel-test and veristat jobs we can save about 1.5 minute of runtime on each job. Job invoking libbpf/ci/run-vmtest action do not need access to the full kernel source tree.
However, this requires an adjustment to the list of the artifacts collected by kernel build. VMLINUZ might be search via `make image_name`, which requires makefiles and other scripts to be accessible.
Example of a failure:
https://github.com/kernel-patches/bpf/actions/runs/12204941090/job/34051427386
Set ARCHIVE_MAKE_HELPERS flag for libbpf/ci/tar-artifacts action to true in kernel-build.
Also, add check for vars.AWS_REGION before executing veristat-meta.
> veristat, kernel-test: fix vmlinuz search

- .github/scripts/matrix.py
- .github/workflows/kernel-build.yml
- ci/diffs/9998-sched_ext-Fix-invalid-irq-restore-in-scx_ops_bypass.patch
- ci/diffs/9999-scx-Fix-maximal-BPF-selftest-prog.patch
Include an upstream patch for selftests/sched_ext
Link: https://lore.kernel.org/all/20241209152924.4508-1-void@manifault.com/
> Re-enable sched_ext test

- .github/scripts/matrix.py
Don't run GCC BPF runner, because too many tests are failing at this point.
See: https://lore.kernel.org/bpf/87bjw6qpje.fsf@oracle.com/
> Disable test_progs-bpf_gcc

- ci/diffs/8888-Revert-netfs-Change-the-read-result-collector-to-onl.patch
- ci/vmtest/configs/DENYLIST.s390x
Examples of failures:
* https://github.com/kernel-patches/bpf/actions/runs/12941732247
* https://github.com/kernel-patches/bpf/actions/runs/12933849075
Suspect upstream commit: e2d46f2ec332533816417b60933954173f602121
https://lore.kernel.org/all/20241216204124.3752367-28-dhowells@redhat.com/
> ci/diffs: temporary patch to mitigate v9fs_evict_inode hanging

- ci/diffs/2000-s390-fgraph-Fix-to-remove-ftrace_test_recursion_tryl.patch
- ci/diffs/2001-s390-tracing-Define-ftrace_get_symaddr-for-s390.patch
- ci/vmtest/configs/DENYLIST.s390x
https://lore.kernel.org/bpf/173807816551.1854334.146350914633413330.stgit@devnote2/
> Fix for missed/kprobe_recursion

- .github/scripts/tmpfsify-workspace.sh
- .github/workflows/kernel-build-test.yml
- .github/workflows/kernel-build.yml
Run kernel build jobs on the runners provided by AWS CodeBuild
service: AWS-hosted environment running our custom docker container
[1] on demand.
This will help handling demand spikes, such as when upstream is merged
into kernel-patches/bpf and workflows are triggered for each pending
patch.
[1] https://github.com/kernel-patches/runner/blob/main/Dockerfile
> kernel-build: implement autoscaling

- .github/workflows/kernel-test.yml
When s390x runners are too busy, test_progs pyperf tests might get killed by a watchdog. Examples:
* https://github.com/kernel-patches/bpf/actions/runs/13644682543/job/38141565931
* https://github.com/kernel-patches/bpf/actions/runs/13644708075/job/38141613357
* https://github.com/kernel-patches/bpf/actions/runs/13644714812/job/38141643246
Double the timeout value to avoid unnecessary workflow failures.
> kernel-test: set TEST_PROGS_WATCHDOG_TIMEOUT to 600 seconds

- .github/scripts/download-gcc-bpf.sh
- .github/workflows/gcc-bpf.yml
> GCC BPF: use pre-built release

- .github/scripts/matrix.py
- .github/workflows/gcc-bpf.yml
- .github/workflows/kernel-build-test.yml
- .github/workflows/kernel-build.yml
Ondemand AWS CodeBuild runners only make sense for kernel-patches/bpf, as this is the main CI repository. In particular, there is no reason to use CodeBuild on bpf-rc.
Control this in the matrix.py script: set build_runs_on to "codebuild" for managed repositories.
> matrix.py: configure codebuild runners

- .github/actions/veristat_baseline_compare/action.yml
This will allow to distinguish between bpf-next and other base branches.
> veristat: include branch name in the cache key

- .github/workflows/test.yml
We have added those 2 branches to be tracked. For CI to run when those get updated, we need to add them to the list of branches to track.
> workflow: Also run the workflow against bpf-net_base and for-next_base

- .github/workflows/kernel-test.yml
This reverts commit a9f85502a4a5912aeded7d0a8baa6c4a2596404d.
There are job failures with this feature on some branches:
* https://github.com/kernel-patches/bpf/actions/runs/14041586178/job/39313704017
* https://github.com/kernel-patches/bpf/actions/runs/14041589098/job/39313608979
> Revert "kernel-test: enable traffic monitoring on x86_64"

- .github/scripts/matrix.py
- .github/workflows/kernel-build.yml
- .github/workflows/test.yml
Currently we always run kernel builds on AWS CodeBuild, which autoscales on demand. However, we still have to maintain bare metal self-hosted runners in order to run selftests. If builds always run on CodeBuild, then the provisioned runners are underutilized.
Implement autoscaling logic in the set-matrix script:
* query github about the status of self-hosted runners
* if they are not busy, use them for builds
* otherwise use CodeBuild
The threshold is set at 80% of online suitable runners being busy.
> set-matrix: smarter autoscaling

- .github/scripts/matrix.py
On codebuild runners, kernel cross-compilation reliably fails with:
/bin/sh: 1:
/codebuild/output/src3696644155/src/actions-runner/_work/vmtest/vmtest/tools/testing/selftests/bpf/tools/sbin/bpftool:
Exec format error
Examples:
* https://github.com/kernel-patches/bpf/actions/runs/14071382414/job/39407043081
* https://github.com/kernel-patches/bpf/actions/runs/14071415023/job/39406288267
* https://github.com/kernel-patches/vmtest/actions/runs/14072569194/job/39409645515
In comparison with recent successful runs, notable change on codebuild runners is the machine's kernel version:
Kernel Version: 4.14.355-275.572.amzn2.x86_64
Kernel Version: 6.1.129-138.220.amzn2023.x86_64
Needs further investigation.
> set-matrix: disable codebuild runners when cross-compiling

- ci/vmtest/configs/DENYLIST.aarch64
It's currently flaky:
* https://github.com/kernel-patches/bpf/actions/runs/14258309884
* https://github.com/kernel-patches/bpf/actions/runs/14258309884
> Add res_spin_lock to DENYLIST.aarch64

- .github/scripts/matrix.py
Cross compilation is broken due to apt packages conflicts. Switch to native builds for now.
See: https://github.com/libbpf/ci/pull/179
> s390x: switch to native builds temporarily

- ci/vmtest/configs/DENYLIST
- ci/vmtest/configs/DENYLIST.test_progs_cpuv4
Turns out arena_spin_lock selftest built with LLVM 20 fails with configs other than cpuv4 runner:
* https://github.com/kernel-patches/bpf/actions/runs/14781515137/job/41501780952
* https://github.com/kernel-patches/bpf/actions/runs/14781517105/job/41501713788
> Disable arena_spin_lock test everywhere

- ci/diffs/20250520-0001-mm-vmalloc-Actually-use-the-in-place-vrealloc-region.patch
- ci/diffs/20250520-0002-mm-vmalloc-Only-zero-init-on-vrealloc-shrink.patch
Recent mm patch [1] causes a regression in BPF verifier which leads to selftest failures. In particular verifier_loops1 test gets killed by the test_progs watchdog [2], although normally it passes in a few seconds.
This has been reported on the mailing list [3], and the fixes are in flight [4]. Add them as CI-specific patches for now.
[1] https://lore.kernel.org/all/20250424023119.work.333-kees@kernel.org
[2] https://github.com/kernel-patches/bpf/actions/runs/15144596086/job/42577510982
[3] https://lore.kernel.org/lkml/20250515-bpf-verifier-slowdown-vwo2meju4cgp2su5ckj@6gi6ssxbnfqg/
[4] https://lore.kernel.org/all/20250515214020.work.519-kees@kernel.org/
> ci/diffs: add patches with vmalloc fixes

- .github/workflows/ai-code-review.yml
- ci/claude/settings.json
Implement a workflow triggering automated AI code reviews for incoming
BPF patches.
The code reviews are executed with Claude Code [1] with elaborate
prompts that instruct LLM to search for particular regressions [2].
In case any regressions are found, LLM is instructed to generate a
conventional inline review, suitable for Linux Kernel mailing list.
[1] https://github.com/anthropics/claude-code-action
[2] https://github.com/masoncl/review-prompts
> Automated AI code review workflow
