travis-ci/vmtest/build_selftests.sh
travis-ci/vmtest/run_vmtest.sh

vmtest: pin Clang/LLVM to version 12 temporarily

---

travis-ci/vmtest/run_vmtest.sh

See https://github.com/libbpf/libbpf/pull/264 for libbpf CI changes.

vmtest: fix clang-13 dependency issues

---

travis-ci/vmtest/build_pahole.sh

Seems like ae2581647e84948810ba209f3891359dd4540110 breaks build
Signed-off-by: Sergei Iudin siudin@fb.com

Pin pahole version to known-working

---

travis-ci/vmtest/run_selftests.sh

Reverts kernel-patches/vmtest#23 due to python3 issue

Revert "ci: do run (previously defined) bpftool_checks"

---

.github/actions/vmtest/action.yml
.github/actions/vmtest/build.sh
.github/actions/vmtest/build_selftests.sh
.github/workflows/test.yml

Signed-off-by: Mykola Lysenko <mykolal@fb.com>

ci: add LLVM support

---

travis-ci/vmtest/configs/blacklist/BLACKLIST-latest
travis-ci/vmtest/run_selftests.sh

Until we fix the regression
Signed-off-by: Mykola Lysenko <mykolal@fb.com>

ci: temporarily disable test_btf_dump_case

---

travis-ci/vmtest/configs/blacklist/BLACKLIST-latest

Signed-off-by: Mykola Lysenko <mykolal@fb.com>

ci: blacklist varlen test temporarily

---

.github/actions/vmtest/build.sh
.github/actions/vmtest/build_selftests.sh
.github/actions/vmtest/helpers.sh
travis-ci/vmtest/helpers.sh
travis-ci/vmtest/run_selftests.sh

This pull request proposes the removal/cleanup of a bunch of Travis remnants.

Clean up Travis remnants

---

ci/vmtest/configs/DENYLIST

denylist: skip verify_pkcs7_sig test while their failure is being investigated

---

.github/workflows/lint.yml
ci/vmtest/helpers.sh
ci/vmtest/run_selftests.sh

Enable the shell linter as in https://github.com/libbpf/ci/pull/61

Shellcheck

---

.github/workflows/test.yml
ci/diffs/0001-net-ipv4-Fix-linux-in.h-header-dependencies.patch
ci/diffs/0002-tools-headers-Pull-in-stddef.h-to-uapi-to-fix-BPF-se.patch

ci: set max CPU to 8 when running qemu

---

ci/diffs/0001-selftests-bpf-Select-CONFIG_FUNCTION_ERROR_INJECTION.patch

Signed-off-by: Song Liu <song@kernel.org>

add patch to fix CI with CONFIG_FUNCTION_ERROR_INJECTION

---

.github/workflows/test.yml

We are still ironing out quirks of parallel test and our s390x capacity would do better if we minimized its usage.

s390x: disable parallel tests

---

.github/workflows/test.yml

Move from branch master and llvm-version.

use main branch from libbpf/ci

---

ci/diffs/0001-veth-take-into-account-peer-device-for-NETDEV_XDP_AC.patch

Fix xdp_bonding to unblock CI.

diffs: fix test_progs xdp_bonding

---

ci/diffs/0001-samples-bpf-drop-unnecessary-fallthrough.patch

Add not-yet-applied patch that fixes samples/bpf build on bpf tree.

diffs: add temporary patch to restore bpf tree build

---

.github/workflows/test.yml

Change arm64 from llvm-17 to llvm-16 and see if it resolves the package not found issue.

Change arm64 to llvm-16

---

.github/workflows/kernel-build.yml

Append `-release` suffix to an artifacts build with `RELEASE=1` optimization

Add suffix for artifacts built with release optimization

---

ci/diffs/0399-selftests-bpf-fix-for-bpf_signal-stalls-watchdog-for.patch

Patch series: https://lore.kernel.org/bpf/20241112110906.3045278-1-eddyz87@gmail.com/

ci: add pending fix for hanging send_signal test

---

.github/workflows/kernel-build.yml
.github/workflows/kernel-test.yml

kernel-build, kernel-test: merge libbpf/ci#150

---

.github/scripts/matrix.py
.github/workflows/kernel-build.yml

Due to: https://lore.kernel.org/bpf/HdoCQccNk3GZdnPx5w1vuAfOMMgtWeUgrUhn_e8B-hyRrWoOPakTGcoI3Q4-QmK_44msuvivoRUykxxeB82uR-S3enkmFaQl2t6Zgu-Nq6Y=@pm.me/

Disable selftests/sched_ext

---

.github/workflows/kernel-build.yml

We'll revert back to master after [1] is landed.
[1] https://lore.kernel.org/dwarves/20250110023138.659519-1-ihor.solodrai@pm.me/

kernel-build: set pahole to v1.28

---

.github/workflows/kernel-build.yml

This reverts commit e598660d33bb76e1cf0228107283606659e40390.

Revert "kernel-build: set pahole to v1.28 (#325)"

---

.github/workflows/kernel-build.yml
.github/workflows/kernel-test.yml
.github/workflows/veristat-kernel.yml
.github/workflows/veristat-meta.yml
ci/vmtest/configs/run-vmtest.env

See  https://github.com/kernel-patches/vmtest/pull/326 and https://github.com/libbpf/ci/pull/166

Merge libbpf/ci#166

---

.github/workflows/gcc-bpf.yml

Fix failures at kernel-patches/bpf:
* https://github.com/kernel-patches/bpf/actions/runs/13165202443/job/36743841891
* https://github.com/kernel-patches/bpf/actions/runs/13165203802/job/36743898124

GCC BPF: fix kernel source checkout at kernel-patches/bpf

---

.github/scripts/matrix.py

This reverts commit bf71b342737fa78ebea60b77e083f99e87883723.

Revert "s390x: switch to native builds temporarily"

---

ci/vmtest/configs/DENYLIST.x86_64

Link: https://lore.kernel.org/all/6f688f2e-7d26-423a-9029-d1b1ef1c938a@linux.dev/

Denylist btf_tag/btf_type_tag_percpu_vmlinux_helper

---

ci/diffs/20250601-0001-selftests-bpf-Fix-bpf-selftest-build-error.patch
ci/diffs/20250601-0002-selftests-bpf-Fix-selftest-btf_tag-btf_type_tag_perc.patch
ci/diffs/20250601-0003-Revert-perf-Only-dump-the-throttle-log-for-the-leade.patch
ci/diffs/20250601-0004-Revert-perf-Fix-the-throttle-logic-for-a-group.patch
ci/vmtest/configs/DENYLIST.x86_64

Link: https://lore.kernel.org/bpf/djxlh5fx326gcenwrr52ry3pk4wxmugu4jccdjysza7tlc5fef@ktp4rffawgcw/

ci/diffs: add patches reverting perf regressions

---

ci/diffs/20250611-veth-prevent-NULL-pointer-dereference-in-veth_xdp_rc.patch

Link: https://lore.kernel.org/bpf/174964557873.519608.10855046105237280978.stgit@firesoul/

ci/diffs: add a bugfix for veth driver

---

ci/diffs/20250627-elftests-bpf-Fix-cgroup_xattr-read_cgroupfs_xattr.patch

Link: https://lore.kernel.org/bpf/20250627191221.765921-1-song@kernel.org

ci/diffs: add patch for cgroup_xattr tests

---

.github/workflows/ai-code-review.yml
ci/claude/post-pr-comment.js

If Claude produced a review file it means it found a potential regression/bug. In that case, post a comment on PR with the inline review and fail the CI job.

ai-code-review.yml: post comments on PRs

---

.github/workflows/ai-code-review.yml

Use https://github.com/masoncl/review-prompts prompts repo

ai-code-review.yml: use masoncl/review-prompts

---

ci/diffs/20251002-Revert-xdp-update-mem-type-when-page-pool-is-used-fo.patch

See: https://lore.kernel.org/bpf/5af7b3b9-3ee1-4ef6-8431-72b40445eacd@linux.dev/

ci/diffs: add a diff reverting ffa327eebccf in netdev tree
